apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: authorino-operator
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  channel: tech-preview-v1
  installPlanApproval: Manual
  name: authorino-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
