kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: "https://github.com/vrutkovs/lyrics-llm"
  name: lyrics-llm
  namespace: ptal-generator
  labels:
    app: lyrics-llm
    app.kubernetes.io/component: lyrics-llm
    app.kubernetes.io/instance: lyrics-llm
    app.kubernetes.io/name: lyrics-llm
    app.kubernetes.io/part-of: lyrics-llm-app
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.12-ubi8
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: "lyrics-llm:latest"
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: "https://github.com/vrutkovs/lyrics-llm"
    contextDir: /
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: lyrics-llm-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: lyrics-llm-github-webhook-secret
    - type: ConfigChange
  runPolicy: Serial
