---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: vrutkovs-9zbw4-worker-us-east-2a
  namespace: openshift-machine-api
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    metadata:
      labels:
        node-role.kubernetes.io/gpu: ""
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/gpu: ""
      providerSpec:
        value:
          instanceType: g5.2xlarge
          preemptible: true
---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: vrutkovs-9zbw4-worker-us-east-2b
  namespace: openshift-machine-api
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    metadata:
      labels:
        node-role.kubernetes.io/gpu: ""
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/gpu: ""
      providerSpec:
        value:
          instanceType: g5.2xlarge
          preemptible: true
---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: vrutkovs-9zbw4-worker-us-east-2c
  namespace: openshift-machine-api
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    metadata:
      labels:
        node-role.kubernetes.io/gpu: ""
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/gpu: ""
      providerSpec:
        value:
          instanceType: g5.2xlarge
          preemptible: true
---
apiVersion: autoscaling.openshift.io/v1beta1
kind: MachineAutoscaler
metadata:
  name: vrutkovs-9zbw4-worker-us-east-2a
  namespace: openshift-machine-api
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: vrutkovs-9zbw4-worker-us-east-2a
---
apiVersion: autoscaling.openshift.io/v1beta1
kind: MachineAutoscaler
metadata:
  name: vrutkovs-9zbw4-worker-us-east-2b
  namespace: openshift-machine-api
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: vrutkovs-9zbw4-worker-us-east-2b
---
apiVersion: autoscaling.openshift.io/v1beta1
kind: MachineAutoscaler
metadata:
  name: vrutkovs-9zbw4-worker-us-east-2c
  namespace: openshift-machine-api
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: vrutkovs-9zbw4-worker-us-east-2c
